// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6IF7b_G_dsnjmJEo0exbq8eURzDe2q-U',
    appId: '1:897377512045:web:e52ae081208e74ae6aed64',
    messagingSenderId: '897377512045',
    projectId: 'crudopt-3fb5c',
    authDomain: 'crudopt-3fb5c.firebaseapp.com',
    storageBucket: 'crudopt-3fb5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_zJ-d0KRqo2UVULzy7aiAujlKiwvP_M',
    appId: '1:897377512045:android:7a755c123ef78fc66aed64',
    messagingSenderId: '897377512045',
    projectId: 'crudopt-3fb5c',
    storageBucket: 'crudopt-3fb5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPFElo03r9cYudGyiw2Lf4OPjCgd7hpl8',
    appId: '1:897377512045:ios:aac1ac9a0bc1e7b86aed64',
    messagingSenderId: '897377512045',
    projectId: 'crudopt-3fb5c',
    storageBucket: 'crudopt-3fb5c.appspot.com',
    iosBundleId: 'com.example.flutterXFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6IF7b_G_dsnjmJEo0exbq8eURzDe2q-U',
    appId: '1:897377512045:web:8ec679e2ad210e946aed64',
    messagingSenderId: '897377512045',
    projectId: 'crudopt-3fb5c',
    authDomain: 'crudopt-3fb5c.firebaseapp.com',
    storageBucket: 'crudopt-3fb5c.appspot.com',
  );

}